<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Company;
use App\Models\MembershipPlan;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $goldPlan = MembershipPlan::where('name', 'Gold')->first();

        if ($goldPlan) {
            // Use firstOrCreate to prevent duplicate errors
            Company::firstOrCreate(
                ['contact_email' => 'billing@testcompany.com'],
                [
                    'name' => 'Test Company Inc.',
                    'status' => 'active',
                    'membership_plan_id' => $goldPlan->id,
                    // 'code' is auto-generated by your observer
                ]
            );
        } else {
            $this->command->warn('Gold membership plan not found. Skipping company creation.');
        }
    }
}