<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Company;
use App\Models\MembershipPlan;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // 1. Find the "Gold" plan created by your MembershipPlanSeeder
        $goldPlan = MembershipPlan::where('name', 'Gold')->first();

        // 2. Create the test company
        if ($goldPlan) {
            Company::create([
                'name' => 'Test Company Inc.',
                'contact_email' => 'billing@testcompany.com',
                'status' => 'active',
                'membership_plan_id' => $goldPlan->id,
                // 'code' is auto-generated by your observer
            ]);
        } else {
            $this->command->warn('Gold membership plan not found. Skipping company creation.');
        }
    }
}