[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan l5-swagger:generate',
    'php artisan migrate --force'
]

[variables]
NIXPACKS_PHP_ROOT_DIR = '/app/public'
NIXPACKS_PHP_FALLBACK_PATH = '/index.php'
