[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'apache2', 'php82Extensions.pdo', 'php82Extensions.pdo_pgsql']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader']

[phases.build]
cmds = [
  'php artisan config:clear',
  'php artisan cache:clear',
  'php artisan route:cache',
  'php artisan view:cache',
  'php artisan l5-swagger:generate'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'
```

Wait, actually the simplest fix is even easier...

## Simplest Fix - Just Change One Thing:

Your `routes/web.php` probably has routes that Laravel is serving on the root, but API routes need the `/api` prefix which is already there.

### Update JUST the Procfile:
```
web: php artisan optimize:clear && php artisan l5-swagger:generate && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT